# Generated by Django 4.0 on 2022-04-17 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembroflia',
            name='fecha_nacimiento',
        ),
    ]
